### ISSUE TITLE
data dictionaries 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#100]
- complete the CDR data dictionary on Data.World 
- complete the OIS data directory on Data.World

**Comment by wetchler** [comment]
Done. @EvaRuthM -- check them out and see if they're to your liking?

**Comment by EvaRuthM** [comment]
I must be looking in the wrong place....nothing [here](https://data.world/tji/officer-involved-shootings/workspace/data-dictionary)

**Comment by wetchler** [comment]
I did not make a data dictionary for the excel file, but if you scroll down on that page you just linked to, to the csv files, you'll see descriptions.

Given that this seems potentially confusing, maybe we should move our "intermediate" files (e.g. the excel file) to a separate repo, so nobody tries to use them? What do you think @EvaRuthM ?

**Comment by EvaRuthM** [comment]
oh! I see now. Yes, I think that's a great idea. I'll make a note on the agenda. Thanks!
