### ISSUE TITLE
audit for 0-9YOs

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#103]
- audit CDR database for reports involving decedents age 0-9 
- audit OIS database for individuals involved age 0-9 
- enter any mistakes in the [Google Sheet here](https://docs.google.com/spreadsheets/d/1u95v-n7evc7nrcPN8TZtLcl9-pbtL_lgpPp-X8GJ5uE/edit#gid=1307012638) so ER can notify report filer

**Comment by wetchler** [comment]
Hey @EvaRuthM -- when you say to "audit" this -- what did you need from me? [Here](https://data.world/tji/deaths-in-custody/workspace/query?queryid=5e5de825-86bf-4eb9-b6f2-5333178fbf08) is a query to get the CDRs of those aged 0-9, and [here](https://data.world/tji/officer-involved-shootings/workspace/query?queryid=c434d7cf-6790-41eb-b035-c4351ef10180) is one to get shot civilians aged 0-9. Or is this not what you needed from me?

**Comment by EvaRuthM** [comment]
Hi @wetchler, that is great. Thank you!
