### ISSUE TITLE
donate pop-up on website

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#122]
create a pop-up that prompts people to donate to TJI when they visit any part of our website. Pop-up should appear once and then disappear when the user dismisses. Pop-up should end altogether on 12/1/2018. 
Text: 
> Donate now and double your impact - all gifts to TJI matched through 11/30! 

(I'm open to edits/suggestions here)

**Comment by EvaRuthM** [comment]
Since our matching challenge has ended, this is no longer immediately needed

**Comment by ifsimicoded** [comment]
@EvaRuthM Sorry sorry sorry I didn't get around to finishing this up sooner. My first work week on the farm left me beat and I just didn't have the energy to work in the evenings. I'll try and put a bow on this, this week. I see no reason to not try the pop up functionality on first view even though the matching challenge has ended.

related to #56 -- the download data button will also prompt the user to make a donation.
