### ISSUE TITLE
rename data column on "officers shot" 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#125]
on "officers shot" data set, please change: 
- Civilian Race 1 
- Civilian Gender 1 
to: 
- Civilian Race 
- Civilian Gender

**Comment by wetchler** [comment]
@EvaRuthM Are you sure we want to do this? There may be up to three civilians involved, so it seems like we should keep the numbering, no?

**Comment by EvaRuthM** [comment]
@wetchler my thinking is that the number "1" needs explanation. So I see a few choices (partial to the first though it's more work): 
- include question: how many civilians/officers involved? 
  - and then demographic information on all, using the numbered headings 
- only include info on first person listed
