### ISSUE TITLE
Bug - broken font awesome icons on staging 

### ISSUE THREAD

**Issue by ifsimicoded** [texas-justice-initiative/website#130]
There is a contact widget/plug-in on staging which is loading font-awesome 4.7.0. This plugin needs to be disabled -- or adjusted such that it doesn't load an independent version of font-awesome which conflicts with our manually loaded font awesome via sass that results in icons being rendered as boxes. See screen below for duplicate load of font-awesome information and resulting squares as icons.

![screen shot 2018-12-02 at 10 02 27 pm](https://user-images.githubusercontent.com/3039125/49355796-04b3bb00-f67e-11e8-96dc-070520b220dc.png)

**Comment by LayaTaal** [comment]
Fixed this issue on staging and also updated staging About page to match production.
