### ISSUE TITLE
Tableau integration

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#149]
create a tab for Tableau dashboards
  - not available on mobile (Tableau isn't responsive and dashboard isn't useful) 
  - example: [here](https://public.tableau.com/profile/james6137#!/vizhome/TJI-DataPortalRedesign/Dashboard_TJI)

**Comment by EvaRuthM** [comment]
@aidenyang, this is the issue related to Tableau. What we'd like is to have a tab on the website for Tableau dashboards like the example above. We have Tableau Desktop for nonprofits, which can connect to a Google Sheet. The problem that I've run into is that I can't get it to connect to any sheets in the Team Drive. I don't want to duplicate the sheets (and therefore duplicate the data sets that need to be updated) and only want to have one place where the data gets updated. So far, that's the only [workaround](https://kb.tableau.com/articles/Issue/Unable-to-connect-to-Google-Sheets-spreadsheet-on-a-Team-Drive) I've found.

**Comment by EvaRuthM** [comment]
hey @aidenyang! I managed to set these up this evening. I now have the spreadsheets on my google drive and can connect to them on Tableau. I'm still trying to figure out through Tableau if I can have multiple users on one account.

**Comment by EvaRuthM** [comment]
[Tableau API integration](https://www.tableau.com/developer)

**Comment by judan** [comment]
https://onlinehelp.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api.htm
