### ISSUE TITLE
Add newsletters to website

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#151]
Goal is to have a place for us to post previous versions of the newsletter, "State of the Data" on the website somewhere.

**Comment by raymondweyandt** [comment]
Hi everyone! I have stored the links to the newsletter issues in the newsletter report here: https://docs.google.com/spreadsheets/d/119TO14kr0Cm4_AJEOrcqmaizJaJNf3nUlldnzlXk6uA/edit#gid=0

There is a column called "Link - Mailchimp" ... links to each issue are provided in that column. 

The "followup" issues are replicas of each newsletter, so we only need to post the main issue. 

Let me know how I can help with this. Happy to discuss during TJI work hour or whenever.

**Comment by raymondweyandt** [comment]
here's another route we can take with this: https://mailchimp.com/help/add-an-email-campaign-archive-to-your-website/

just an idea!

**Comment by EvaRuthM** [comment]
please put these on the "publications" sidebar for now
