### ISSUE TITLE
add 2019 to filters

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#153]
Edit filters on Explore the Data pages to include "2019" as an option for Year.

**Comment by ifsimicoded** [comment]
@EvaRuthM - a developer shouldn't need to update any javascript code to add filters. If the data contains 2019 data points, those filters will automatically get added. Maybe staging and the live site do not have updated data sets.

**Comment by EvaRuthM** [comment]
hi @ifsimicoded, our google sheets data is updated but I believe in the automation process, there were some links that needed to be changed.
