### ISSUE TITLE
Explore Data - Add button to download filtered data

### ISSUE THREAD

**Issue by wetchler** [texas-justice-initiative/website#17]
Note this will require:
- [ ] Somehow converting our data json object into a csv in javascript
- [ ] Probably pulling the FULL dataset, so they don't just download the 8ish columns we are displaying here
- [ ] stretch goal could be to add download button for each chart (I think this is build in functionality for chart.js charts)

**Comment by EvaRuthM** [comment]
YES to pulling the FULL dataset or most of it - I think the downloaded data should also include the names of individuals since we don't have names elsewhere
