### ISSUE TITLE
Create storymap slides for bail deaths project

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#174]
using [storymap.js](https://storymap.knightlab.com/), give facts about four/five individuals who have died in Texas jails on bail (awaiting trial) 
[more details](https://docs.google.com/document/d/11E4t48W496kUdGgZCkcGSIQhwNKYh0DuqdaWASq9BA4/edit)

Storymap in progress: [here](https://uploads.knightlab.com/storymapjs/e28d75a4c594f354a455baf2a3dbb81e/pre-trial-deaths-in-texas-jails/draft.html)

**Comment by raymondweyandt** [comment]
Deadlines, per 3/20 marketing meeting:
3/24 - final draft of slides for TJI meeting

**Comment by EvaRuthM** [comment]
[Raymond's project](https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1VAOnZfKUNbIT9vLlFZH0Mp-OPRtRQdSiKPin2iUa-1E&font=Default&lang=en&initial_zoom=2&height=650)
