### ISSUE TITLE
presser for jail deaths project

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#176]
send out press release related to James' Tableau project on bail deaths 
[more details](https://docs.google.com/document/d/11E4t48W496kUdGgZCkcGSIQhwNKYh0DuqdaWASq9BA4/edit)

**Comment by EvaRuthM** [comment]
press release draft [here](https://docs.google.com/document/d/1dbsqnSbVy7PNi20mTbU6_AxrQZbEDYCmeDrxdxsAOIg/edit)

**Comment by raymondweyandt** [comment]
target send date: 4/2/2019

**Comment by EvaRuthM** [comment]
[SQL query in data.world](https://data.world/tji/deaths-in-custody/workspace/query?queryid=b36e165f-c3a3-4eb6-931f-bcafeafe9eee) for those who want to probe the data set

**Comment by raymondweyandt** [comment]
Hi @EvaRuthM - I have finished the edits and double checking the numbers in the presser. It is ready for your review. Thank you for the guidance!
