### ISSUE TITLE
7/1 meeting agenda items

### ISSUE THREAD

**Issue by wetchler** [texas-justice-initiative/website#19]
Feel free to add your own below, adding your name so we know whose item it is.

- Code reviews with Github Workflow (@ifsimicoded / @wetchler)
- Project management with Github Projects, Milestones, and tagging (@ifsimicoded)
- New Issues discussion, assign owners and set deadlines (Backlog Grooming) - @ifsimicoded
  - #20, #17, #16
  - set deadlines (queue up for upcoming week if necessary), assign owners 
- Current Status of open/in progress issues (Sprint Planning/Review) -@ifsimicoded
  - any blockers?
- User testing (@wetchler)
- Documentation (github wiki and readme) (@ifsimicoded)

**Comment by ifsimicoded** [comment]
- Hiring - no hierarchy, except Eva runs the show
- Board member hunt
  - Amanda's flux-y level of involvement
- Fundraiser
  - goal: $5000 / up for 2 months
  - $1000 foundation grant
- Github for Project Management
  - Milestones for scheduling releases and tracking completion of tasks for releases
  - Labels for features/bugs/technical debt
  - Pull Requests for code review (tag issues like: `closes #3` that are related to the code you're asking for review on)
  - Projects like trello / pipeline for issues (open, in progress, in review, done)
