### ISSUE TITLE
Make map of shootings by location (of shooting) 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#27]
Google Map -- using geocoding created by Dash. 
- locations are location of death for CDR and location of police shooting

**Comment by ifsimicoded** [comment]
some helpful documentation on google map clustering
https://developers.google.com/maps/documentation/javascript/marker-clustering

**Comment by EvaRuthM** [comment]
This is what the Google for Nonprofits offers for Maps: 
"Apply for Google Maps Platform credits. Build websites and applications with Google's reliable, comprehensive location, traffic and places data. For more information about Google Maps Platform products and pricing, visit our [website](https://cloud.google.com/maps-platform/#get-started)."

**Comment by EvaRuthM** [comment]
render map with pins and clusters; build on new page with filters

**Comment by EvaRuthM** [comment]
example for data on Texas county jails: `https://txappleseed.github.io/txappleseedmap/`
2/24 - TJI work hour with CenTex Mapathon
