### ISSUE TITLE
Donate form

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#31]
<h1>Elevating our Donate Button</h1>
Build a form for online donations that users would find via the Donate Button (instead of the Facebook fundraiser campaign). Here are a couple of examples of what I'm thinking: 

* [Rivard Report](https://therivardreport.com/donate/)
* [Texas Tribune](https://checkout.texastribune.org/donate?installmentPeriod=once&amount=60&_ga=2.209388178.1861072604.1530904575-1285616915.1530397542)

**Comment by EvaRuthM** [comment]
Information to obtain from donors in form: 
Name
Email address (if agree to opt-in to receive our newsletter)
ZIP code 
Why are you supporting TJI? (fill in the blank - 50 word limit) 
User type (choose all that apply: "researcher", "reporter", "policy analyst", "lawyer", "interested citizen")

**Comment by ifsimicoded** [comment]
Closing as the first round of the donate form is complete. There's a new open issue to make attach the donate form to the download button #56 , which will address the additional user info logging requirements.
