### ISSUE TITLE
Explore Data - Browser Test

### ISSUE THREAD

**Issue by ifsimicoded** [texas-justice-initiative/website#35]
Test the explore data page in a pre-determined list of browsers and devices. 
@EvaRuthM can you provide a list of these that you'd prefer us to support-- if you're flying blind, I can provide what big companies tend to support.

*to do by 7/28*

**Comment by EvaRuthM** [comment]
I used [Browserling](https://www.browserling.com/) to see our current site in Internet Explorer - everything seems to be working correctly and it's responsive. Browserling also has a free chrome plug-in that I can install to test with all their options.
