### ISSUE TITLE
Tweak homepage slider and icon nav section

### ISSUE THREAD

**Issue by judan** [texas-justice-initiative/website#41]
- Make slider section height smaller (more above-the-fold real estate for next section)
- Move pagination icons to bottom of slider
- Add dynamic numbers to slider stats (they're hardcoded right now)

**Comment by ifsimicoded** [comment]
Hey @judan, since swiper also has some dependency with a security issue, could we find another slim slider library to use. maybe bootstrap since we're using some of their sass also?
