### ISSUE TITLE
change M and F to "male" and "female" 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#75]
On "Explore the Data" pages, change the key on chart analyzing gender from "m" and "f" to "male" and "female"

**Comment by wetchler** [comment]
Closed by commit [53d8cdbe](https://github.com/texas-justice-initiative/data-processing/commit/53d8cdbe15432db54f1ac60ef245a843194d9d2a) in the data-processing repo

**Comment by wetchler** [comment]
Whoops, forgot I need to check data in here, hang on
